import Head from "next/head";
import { Fragment } from "react";

export default function sellNft() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Fragment>
        <div>
          <h1>Nft-details</h1>
        </div>
      </Fragment>
    </>
  );
}
